INSERT INTO
    students(
        "name",
        "email",
        "module",
        "score",
        "active"
    )
VALUES
(
        'Enzo',
        'enzo@email.com',
        'M3',
        '85',
        TRUE
    ),
    (
        'Valentina',
        'valentina@email.com',
        'M4',
        '97',
        TRUE
    ),
    (
        'Osvaldo',
        'osvaldo@email.com',
        'M5',
        '65',
        FALSE
    );